### ISSUE TITLE
Insert method panicked with "Tried to insert into filled index"

### ISSUE THREAD

**Issue by zonyitoo** [carllerche/slab#16]
It is a little bit tricky to reproduce this error. But it can be reproduce 100% in my project `shadowsocks-rust`.

I just refactoring my `coio-rs` these days, and it keep panicking on this line: https://github.com/carllerche/slab/blob/master/src/lib.rs#L153.

I want to ask in what condition, this line will be called?

Detail:

In my code, I would call the `insert` method when I want to `register` an event in the EventLoop, see [here](https://github.com/zonyitoo/coio-rs/blob/master/src/scheduler.rs#L349). And when I got the event, I would `remove` the token in the Slab immediately, see [here](https://github.com/zonyitoo/coio-rs/blob/master/src/scheduler.rs#L77). I don't know why this panic is triggered.

**Comment by zonyitoo** [comment]
@dpc I saw you added this line, maybe you could help me?

**Comment by zonyitoo** [comment]
Ok, I have found the problem. Just because that I have already messed up with the stack.

**Comment by hjr3** [comment]
@zonyitoo i was unavailable for the past week. glad to see you have resolved it!
