### ISSUE TITLE
README with example

### ISSUE THREAD

**Issue by tadman** [carllerche/slab#21]
Since this has been split off into a separate repository it's missing the usual README jazz. There's not really much in the way of hints as to how to use this properly other than the source, nor why someone would even want to use it in the first place.

Just a note. The only reason I'm here is because of `mio` but it'd be nice to know more about this particular library and how it might work in other projects.

**Comment by xudifsd** [comment]
+1 for mio, I also want to read some examples to see if it's right for my usage.

**Comment by stjepang** [comment]
I have a similar crate, [vec-arena](https://github.com/stjepang/vec-arena), with a README and two examples.

Would it make sense to write a similar README for slab and port my examples? @carllerche, what do you think?

**Comment by carllerche** [comment]
Merged in master!
