### ISSUE TITLE
Possible bug with repeated removes

### ISSUE THREAD

**Issue by pacheco** [carllerche/slab#22]
The following sequence of operations will panic on the last `insert`.

    let mut s = Slab::<(), usize>::new_starting_at(0, 10);
    let t1 = s.insert(()).unwrap();
    let t2 = s.insert(()).unwrap();
    assert!(s.remove(t2).is_some());
    assert!(s.remove(t2).is_none());
    assert!(s.remove(t1).is_some());
    assert!(s.remove(t1).is_none());
    s.insert(());
    s.insert(());

Since `remove` can return `None`,  I would expect repeated removes to work.

**Comment by pacheco** [comment]
Found the problem. `remove()` replaces the removed slot with `Empty(self.next)`.
The problem is, when the slot is _already_ empty it should leave it as is, replacing it with `self.next` does the wrong thing...

**Comment by dpc** [comment]
Great find! Can you create a PR with a test and fix?
