### ISSUE TITLE
Confused (usize assert).

### ISSUE THREAD

**Issue by quadrupleslap** [carllerche/slab#24]
```
pub fn new_starting_at(offset: I, capacity: usize) -> Slab<T, I> {
    assert!(capacity <= usize::MAX, "capacity too large");
    ...
}
```
[Link](https://github.com/carllerche/slab/blob/133d6bd19f10d1de508077d4dd2c8625200c79f2/src/lib.rs#L74)

I'm confused - isn't a `usize` **always** less than or equal to `usize::MAX`?

**Comment by dpc** [comment]
Interesting `capacity` is `usize` it seems, so I think you're right.

**Comment by quadrupleslap** [comment]
lol, I forgot to mention that key point in the OP. Thanks!

**Comment by carllerche** [comment]
This was a bug... there was supposed to be a `- offset`... oops! This was fixed though :)
