### ISSUE TITLE
Inserts at arbitrary position may break list of free entries.

### ISSUE THREAD

**Issue by tmiasko** [carllerche/slab#26]
In example below slab has space for 10 entries, but inserting at last index
will replace Slab::next with 10, and subsequent inserts will fail, even though
there are still plenty of vacant entries left:

    #[test]
    fn test_entry_insert_breaks_next() {
        let mut slab = Slab::<usize, usize>::new(10);
        assert_eq!(&42, slab.entry(9).unwrap().or_insert(42));
        assert!(slab.has_remaining());
        assert!(slab.insert(82).is_ok()); // panics
    }

To insert entry at index idx, slab would have to locate an entry with next
equal to idx, and update its next value. Doing this efficiently would require
double linked list. It seems that exposing this functionality as it is
currently done, is kinda dangerous.

**Comment by carllerche** [comment]
Good eye... exposing that API was definitely not intended. It is a bug.

**Comment by tmiasko** [comment]
Fixed after your last library overhaul, closing.
