### ISSUE TITLE
Methods to auto-grow on insert

### ISSUE THREAD

**Issue by 17dec** [carllerche/slab#29]
While a fixed-size slab has its uses, it's sometimes more convenient/efficient use a dynamically growing one. For that purpose I've been using the following function internally:

``` rust
fn slab_insert<T, I:Into<usize>+From<usize>>(s: &mut Slab<T,I>, t: T) -> I {
    s.insert(t).or_else(|t| {
        // Grow by some small fixed number. From what I can see the Slab implementation already
        // does exponential growth internally.
        s.reserve_exact(8);
        s.insert(t)
    }).unwrap_or_else(|_| { unreachable!() })
}
```

I figured it might be useful to have similar functionality provided by the crate itself.

What I propose is to add a two new methods, mimicking their non-_grow counterpart, except these methods will automatically grow if there is not enough space. They do not (need to) return a Result, as they cannot fail.

``` rust
fn vacant_entry_grow(&mut self) -> VacantEntry<T, I>
fn insert_grow(&mut self, val: T) -> I
```

I'd be happy to provide a PR, but was interested in getting some feedback before moving on.

**Comment by carllerche** [comment]
I've been thinking about this in the past, and my thought was to initialize the `Slab` w/ an initial capacity & a max capacity. Then `insert` will grow on demand until the max capacity is reached. The current behavior can be obtained by setting the initial capacity & max capacity to the same value.

So, the following changes would be made:

* Internally, the `Slab` has a max_capacity setting
* Initial capacity & max capacity must both be powers of 2
* When an `insert` needs capacity, the slab size is doubled
* If the initial capacity is set to 0, the initial grow is a constant (probably 32).

I would leave `Slab::with_capacity` as a default for setting initial capacity == max capacity, which means there needs to be an alternate way to configure, maybe a builder struct.

```rust
struct Builder<T> { ... }

impl Slab<T> {
    fn configured() -> Builder<T> { ... }
}

let slab = Slab::configured()
    .initial_capacity(128)
    .max_capacity(4_096)
    .build();
```

**Comment by 17dec** [comment]
That seems slightly more work that I had anticipated, but being able to configure the Slab object itself to autogrow definitely provides a nicer API than my suggestion.

I'll play around and see if I can implement your suggestion. I'm a bit confused by your example though, did you intend it like this?
```rust
struct Builder { ... }

impl Builder {
    fn new() -> Builter { ... }
}

let slab : Slab<T,I> = Builder::new().etc().build();
```
I'm not sure if there's a standard on creating Builder structs, mio::timer::Builder seems to use the Default trait and there's std::thread::Builder using new() as above. I have a slight preference for new(), but either way works for me.

**Comment by 17dec** [comment]
That's an initial working version. A few notes:

1. I couldn't really think of a default capacity, so Builder::new() requires a specifying a capacity already; The max capacity in this case.
2. I wasn't exactly sure what to do with reserve_exact(). In the hopes of not breaking existing code that still works with initial_capacity = max_capacity, I've changed its behaviour to adjust the max_capacity as necessary while still keeping it a power of two. The name of the method is rather misleading now.
3. Some tests made assumptions about the non-power-of-two capacities that the Slab used to work with. I've updated these since the Slab now works with power-of-twos everywhere.

**Comment by stjepang** [comment]
I just wrote a similar crate, [vec-arena](https://github.com/stjepang/vec-arena). It grows the internal buffer automatically. It's a bit silly that we're duplicating our efforts :)

With that in mind, I don't understand several concerns here:

1. Why must initial_capacity and max_capacity be powers of two? What do we gain from that?
2. Why not simply have default capacity of zero? `Vec` works that way.
3. Why would there exist max_capacity anyway? Is it not easy enough to `assert!` that length is `<=` than capacity after every insert into slab?

**Comment by carllerche** [comment]
1. powers of two are cleaner. They allow for checks and growth to be bit operations vs. "more expensive" arithmetic ops.
2. The reason I initially wrote `Slab` was to get zero runtime allocation by preallocating necessary memory. To be able to satisfy this goal, you need to be able to set an initial capacity.
3. I would prefer to keep the current API of returning `Options`. It keeps the code that enforces the limits in one place vs. spread out across all usage. If you forget to add a check in one place that inserts into the slab, the bound is broken.

**Comment by stjepang** [comment]
1. Growth by factor 2 is always bitwise shift, regardless of current capacity. What checks exactly in this crate benefit from the capacity being a power of 2?
2. Yes, but we could simply have a `Slab::new()` and `Slab::with_capacity(cap)`, just like `Vec` does.
3. Okay, that's fair. It would be convenient to have an optional bound on capacity.

My general sentiment is that `Slab` is a lot like `Vec`. In fact, it essentially **is** just a wrapper around `Vec<Option<Slot<T>>>`. Having a familiar `Vec`-like interface would be beneficial to users.

**Comment by carllerche** [comment]
Master auto grows now.

**Comment by stjepang** [comment]
Thank you! I believe now we have everything I ever wanted from this crate.
