### ISSUE TITLE
insert_at public method

### ISSUE THREAD

**Issue by TrionProg** [carllerche/slab#30]
Hello, I use slab to storage objects that has invariant index, but I need storage other object with same index. Yes, then slab won't be just allocator, but this is useful and importend - I do not want to make forks/copypaste

**Comment by stjepang** [comment]
I believe `slab.vacant_entry(index).unwrap().insert(value)` does what you want.

**Comment by carllerche** [comment]
Unfortunately, one cannot insert a value at a predefined slot. This would break the internal state. If you have invariant indexes maybe a Vec would work?
