### ISSUE TITLE
Documentation page docs.rs/slab is broken

### ISSUE THREAD

**Issue by realcr** [carllerche/slab#51]
Hi,
When I click on the documentation link of this repository, I am redirected to https://docs.rs/slab.
I get the following error with my browser:
```
Your connection is not secure

The owner of docs.rs has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
```

I think that this is related to misconfiguration of certificates.
I am using firefox 60.0.2 (64 bit) on Ubuntu.

**Comment by carllerche** [comment]
This seems to be a docs.rs. bug. I believe they fixed it.

Closing as there is no action on our part.
