### ISSUE TITLE
Implement `Slab::reserve()`.

### ISSUE THREAD

**Issue by dpc** [carllerche/slab#7]
I would like an ability to resize a Slab with `Vec::reserve()`-like call.

Is there any reason why `Slab::entries` are not just `Vec<Entries>`? That would make this change trivial, it seems to me.

**Comment by carllerche** [comment]
I think that with the initial implementation using `Vec` was more work, but there have been refactors since. I would be happy w/ a PR that switched to `Vec` if it reduces code w/o adding any overhead.

**Comment by carllerche** [comment]
Fixed on master.
